image: gradle:8.4

build:
  stage: build
  script:
    - gradle buildPlugin

deploy-jar::
  stage: deploy
  needs:
    - build
  rules:
    - if: '$CI_COMMIT_TAG'
      when: on_success
    - when: never
    - when: manual
  script:
    - echo "deploy"

