image: gradle:7.0

build:
  stage: build
  script:
    - gradle init

build-deploy-jar:
  stage: deploy
  script:
    - gradle init
    - gradle jar
  artifacts:
    paths:
      - build/libs/gitlab-pipelines*
