image: gradle:8.4

build:
  stage: build
  script:
    - gradle buildPlugin

upload-repo:
  stage: deploy
  rules:
    - when: manual
  script:
    - 'curl -L --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file updatePlugins.xml "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/plugins-repo/1.0.0/updatePlugins.xml"'

upload-plugin:
  stage: deploy
  needs:
    - build
  rules:
    - if: '$CI_COMMIT_TAG'
      when: on_success
    - when: never
    - when: manual
  script:
    - gradle buildPlugin
    - ls ./build/distributions/Gitlab-Pipelines-${CI_COMMIT_TAG}.zip
    - 'curl -L --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file "./build/distributions/Gitlab-Pipelines-${CI_COMMIT_TAG}.zip" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/gitlab-pipelines-plugin/${CI_COMMIT_TAG}/Gitlab-Pipelines.zip"'


