image: gradle:7.0

build:
  stage: build
  script:
    - gradle init
    - gradble build

deploy-jar::
  stage: deploy
  needs:
    - build
  rules:
    - if: '$CI_COMMIT_TAG'
      when: on_success
    - when: never
    - when: manual
  script:
    - echo "deploy"

