image: gradle:11-jdk-openj9

test-tags:
  only:
    refs:
        - tags

  stage: test
  script:
    - gradle test
  artifacts:
    when: always
    reports:
      junit: build/test-results/test/**/TEST-*.xml
