image: gradle:8.4

build:
  stage: build
  script:
    - gradle buildPlugin

upload-jar:
  stage: deploy
  needs:
    - build
  rules:
    - if: '$CI_COMMIT_TAG'
      when: on_success
    - when: never
    - when: manual
  script:
    - gradle buildPlugin
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file build/libs/gitlab-pipelines* "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/gitlab-pipelines-plugin/gitlab-pipelines.jar"'


