image: gradle:8.4

build:
  stage: build
  script:
    - gradle buildPlugin

upload-plugin:
  stage: deploy
  needs:
    - build
  rules:
    - if: '$CI_COMMIT_TAG'
      when: on_success
    - when: never
    - when: manual
  script:
    - gradle buildPlugin
    - ls ./build/distributions/Gitlab-Pipelines-${CI_COMMIT_TAG}.zip
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file updatePlugins.xml "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/gitlab-pipelines-plugin/updatePlugins.xml"'
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file "./build/distributions/Gitlab-Pipelines-${CI_COMMIT_TAG}.zip" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/gitlab-pipelines-plugin/gitlab-pipelines.zip"'


