image: gradle:latest

java:
  only:
    refs:
        - tags
    variables:
        - $CI_COMMIT_TAG =~ /^test[0-9]*$/

  stage: test
  script:
    - gradle test
  artifacts:
    when: always
    reports:
      junit: build/test-results/test/**/TEST-*.xml